repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0
    hooks:
      - id: isort
        args: [--profile, black]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --strict]

  - repo: https://github.com/adamchainz/flake8-pyi
    rev: 23.7.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-docstrings

  # Локальный хук для обнаружения «...» без обработки
  - repo: local
    hooks:
      - id: detect-bare-ellipsis
        name: Detect bare ellipsis in Python code
        entry: grep -nR "^\s*\.\.\.\s*$" --include \*.py .
        language: system
        types: [file]
        pass_filenames: false
        always_run: true
