version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      # Эти значения должны совпадать с теми, что вы прописали в DATABASE_URL
      POSTGRES_USER: vpnsell_user
      POSTGRES_PASSWORD: vpnsell_pass
      POSTGRES_DB: vpnsell
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    build: .
    env_file: .env
    restart: unless-stopped
    depends_on:
      - db
    # если хотите подключить локальный каталог для разработки:
    # volumes:
    #   - .:/app

volumes:
  db_data:
