services:
  bot:
    build: .
    command: >
      sh -c "
      python scripts/init_db.py &&
      python -m vpnsellbot.main"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: vpnsell
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
